### ISSUE TITLE
test_opening_every_category_page_from_categories_menu isn't actually running

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/marketplace-tests#610]
I noticed something strange when I ran `test_opening_every_category_page_from_categories_menu` locally, and I am seeing it to on the Saucelabs run [1]. Although the test runs and passes, it doesn't seem to open *any* of the category pages, let alone all of them! So it looks like there is something seriously wrong with the test.

[1] https://saucelabs.com/jobs/bbb8c652a7384fe4b7574d684cdbd58c

**Comment by AndreiH** [comment]
As mentioned in https://github.com/mozilla/marketplace-tests/pull/591, I resolved the problem by changing the locator to be the correct one.
<code>test_opening_every_category_page_from_categories_menu</code> was failing because <code>home_page.category_count</code> was returning <code>init:0</code>
Let's modify the test to make sure this never happens again if the locator changes

**Comment by bobsilverberg** [comment]
@AndreiH This test is having all kinds of failures on CI. It seems like there must be a way to make the test more stable. Can you take a look when you get in tomorrow. It's failing consistently on marketplace.prod and marketplace.dev, but the saucelabs runs seem less consistently faily.

**Comment by AndreiH** [comment]
@bobsilverberg I have run this test locally for tens of times and it didn't reproduce.
Since the Saucelabs failures were different I increased the <code>--timeout</code> of the jobs from 300 to 400 as the test takes quite a bit to complete. After that modification, all Saucelabs jobs passed without problems.
As for the inhouse jobs, I tried different <code>waits</code> and <code>time.sleeps</code> here and there, where I thought that would help, but without any luck :(
If you want to see the commits see: http://selenium.qa.mtv2.mozilla.com:8080/view/Marketplace/job/marketplace.DEV.issue_610/

**Comment by bobsilverberg** [comment]
@AndreiH I cannot reproduce it locally either. :(

If the test truly takes that long to complete, then we should try to shorten it. I think it is now doing a bit more than it has to, checking each app on each page. Maybe we could just check the first one or two apps, and maybe we could open a random assortment of categories instead of all categories.

@krupa What do you think? The test seems to be quite unstable in its current state. Can we still have decent test coverage if we do not always open every category page, and if we check for visibility of items for only some apps instead of all apps on the page?

**Comment by AndreiH** [comment]
It seems that the test started passing on our inhouse VMs http://selenium.qa.mtv2.mozilla.com:8080/view/Marketplace/job/marketplace.DEV/

**Comment by rbillings** [comment]
It looks like the last time this test failed was 2/17/15, but has been passing ever since. 
https://webqa-ci.mozilla.com/job/marketplace.dev/

**Comment by bobsilverberg** [comment]
I have submitted PR #639 that addresses this test, which is also discussed in issue #638. I'm going to close this issue.
